### ISSUE TITLE
RPM logo could not be found

### ISSUE THREAD

**Issue by pvalena** [developer-portal/website#119]
https://developer.fedoraproject.org/static/logo/rpm.png

Referenced from:
https://developer.fedoraproject.org/deployment.html

Although it exists:
https://github.com/developer-portal/website/blob/master/static/logo/rpm.png

Probably some jekyll build / distribution issue.

**Comment by jackorp** [comment]
When I `curl` the image it has 0 length.

The release repo also has 0 length rpm.png: https://github.com/developer-portal/developer.fedoraproject.org/blob/release/static/logo/rpm.png

Probably some sync issue?

The logo is present correctly when I serve the site or run `jekyll build` in devel container.

**Comment by pvalena** [comment]
Yes, but it's not there even after the web page update. Also on staging it's missing all the same:

https://developer.stg.fedoraproject.org/static/logo/rpm.png

Maybe let's just re-upload it?

**Comment by pvalena** [comment]
*manually force remove + re-add to git with new build.*

**Comment by jackorp** [comment]
Fixed by newest commit to `developer.fedoraproject.org` repo: https://github.com/developer-portal/developer.fedoraproject.org/commit/d801613793b278bf1333b6e14bc4e8c9047c892d

Present on staging https://developer.stg.fedoraproject.org/deployment.html
