### ISSUE TITLE
Add subsection image for Virtualization inside the Tools section

### ISSUE THREAD

**Issue by t0xic0der** [developer-portal/website#121]
I am trying to introduce a new subsection with the PR https://github.com/developer-portal/content/pull/394 but it cannot be merged yet as the subsection does not have a logo.

Noting that the section that I am talking about here was newly introduced by me with this pull request. Here's the log.

```
podman run -it --rm -p 4000:4000 -v "$PWD:/opt/developerportal/website/content:Z" quay.io/developer-portal/devel
```

```
Configuration file: /opt/developerportal/website/_config.yml
            Source: /opt/developerportal/website
       Destination: /opt/developerportal/website/_site
 Incremental build: enabled
      Generating... 
       Git authors: Generating authors...
Traceback (most recent call last):
  File "/opt/developerportal/website/rss.py", line 23, in <module>
    feedparser._HTMLSanitizer.unacceptable_elements_with_end_tag.add('<div>')
AttributeError: module 'feedparser' has no attribute '_HTMLSanitizer'
                    done in 6.125 seconds.
 Auto-regeneration: enabled for '/opt/developerportal/website'
LiveReload address: http://0.0.0.0:35729
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
[2021-09-08 02:14:07] ERROR `/static/logo/virtualization.png' not found.
[2021-09-08 02:14:14] ERROR `/static/logo/virtualization.png' not found.
[2021-09-08 02:14:22] ERROR `/static/logo/virtualization.png' not found.
```

**Comment by t0xic0der** [comment]
Here are some screenshots.

![v02](https://user-images.githubusercontent.com/49605954/132436264-4520df49-7bb2-46de-b271-d3c7c32f43ee.png)

![v01](https://user-images.githubusercontent.com/49605954/132436268-6cfef7d1-0c47-4b4c-ae05-fa9e45e59c85.png)

**Comment by jackorp** [comment]
Hmm, this is not a broken container image but a missing logo.

An image is needed, must have an open-source license, format preferably png that will have the path `website/static/logo/virtualization.png`, named after the subsection, after that the logo should be visible in the virtualization page.

For licenses, Fedora has a [list of "good/bad" licenses](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing) which could be a good source should you be unsure if some image can be redistributed.

Please reach out if you have any further questions.
