### ISSUE TITLE
Link back to the Content repo from each page

### ISSUE THREAD

**Issue by asamalik** [developer-portal/website#23]
We should link back to the Content repo from each page to attract contributors.

**Comment by strzibny** [comment]
Something like `edit/fix this page`? Yeah. Could be next to the link to Ask Fedora.

**Comment by asamalik** [comment]
Agree.

**Comment by asamalik** [comment]
Done. You can preview here: http://developer.fedorainfracloud.org/tech/languages/ruby/ruby-installation.html
