### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by strzibny** [developer-portal/website#26]

**Comment by phracek** [comment]
Yeah, we should definitely define it.

I guess, that developer.fedoraproject.org is based on our report https://github.com/developer-portal/developer.fedoraproject.org

But it would be good to take it from https://developer.stg.fedoraproject.org/ machine, though.

We should definitely discuss it with @sticker or @robyduck

**Comment by strzibny** [comment]
This is now done in `RELEASE.md`.
