### ISSUE TITLE
Resolve developers.fedoraproject.org in addition to developer.fedoraproject.org

### ISSUE THREAD

**Issue by ncoghlan** [developer-portal/website#28]
Sites vary in whether they put their developer portals at "developer.domain" or "developers.domain", making it difficult to remember which sites use the plural form and which don't.

Red Hat put their portal at developers.redhat.com, with developer.redhat.com as an alias.

The Fedora portal is at developer.fedoraproject.org, but developers.fedoraproject.org doesn't exist in DNS.

It would be helpful if the latter domain resolved as an alias for the Fedora Developer Portal.

**Comment by phracek** [comment]
Good point.
I have created a ticket for it. https://fedorahosted.org/fedora-websites/ticket/364

**Comment by ncoghlan** [comment]
Thanks! With an infra ticket created, I don't think we need the GitHub issue any more.
