### ISSUE TITLE
Website takes too long to load

### ISSUE THREAD

**Issue by sonalkr132** [developer-portal/website#31]
The homepage of website took total of 48.87 seconds to load and downloaded 3.2 MB. It is mostly a static website, it shouldn't really use that much data (or time).
Some of the easy wins I can think are:
* compress and optimize `title_front.png` 

      currently 1.9 MB and should not be more than 100KB after optimization for web.
*  jquery.dataTables.js is not minified (~$400KB)
* `index.json` file is too big (~500KB)

    Since the project is still in development, json file will most like keep growing. It would best to devide         the data in multiple files and load only relevant data.

Someone please look into this if I don't send a PR soon enough.

**Comment by asamalik** [comment]
Thanks for reporting! I'm currently working on some minor UI changes and I will include these optimizations as a part of the changes.

**Comment by strzibny** [comment]
This is known issue, especially the images, and I completely agree -- we need to optimize it.

**Comment by asamalik** [comment]
fixed and deployed to testing http://172.17.0.2:8080/
