### ISSUE TITLE
Mention contributors on respective pages

### ISSUE THREAD

**Issue by asamalik** [developer-portal/website#38]
Let's give credit to our contributors!

Could we for example run 'git blame' during build and get a list of contributors for each page?

We could then put the names (top 5 or all?) on every page.

@pvalena as you were interested in the automated deployment of our testing instance, do you want to have a look at that?

**Comment by pvalena** [comment]
Sounds good. Yes, I will look at it :)
 
Regarding the 'top x'- I think there could be some calculation using [per person]:

> (number of commits * number of lines commited avg) x (total + last month)

What do you think? @asamalik

**Comment by phracek** [comment]
I would prefer top 5.
May be average of commits. Keep it simple is the best solution, I guess.

**Comment by pvalena** [comment]
Another Idea: Github has some statistics in 'Graphs'  (probably accessible via API) we could use.

**Comment by pvalena** [comment]
Prototype[WIP]: https://github.com/developer-portal/tools/blob/master/get_authors.rb

**Comment by pvalena** [comment]
Implemented now.
