### ISSUE TITLE
Links from search stopped working

### ISSUE THREAD

**Issue by strzibny** [developer-portal/website#40]
They have `content/` part in their URL.

@asamalik I suspect this happened with the latest deploy.

**Comment by voxik** [comment]
Can confirm that. I searched for 'ruby' and got the following link:

https://developer.fedoraproject.org/content/tech/languages/ruby/ror-installation.html

**Comment by pvalena** [comment]
Searching seems to work fine for me [1]. Can you please confirm?

[1] https://developer.fedoraproject.org/search.html?q=ruby

**Comment by strzibny** [comment]
@pvalena it works unless you mess up the build :). Adam made a mistake once....your release works. Closing.
