### ISSUE TITLE
Jekyll permission error in Docker container

### ISSUE THREAD

**Issue by frenzymadness** [developer-portal/website#47]
Hello.

I want to contribute to fedora developers portal and I want to check my changes before I make a pull request so I decided to install development version to my local machine in docker container.

When I run:

`$ sudo docker run -it --rm  developerportal/devel`

Everything is ok. But when I want to use my own copy of content repository as volume:

`$ sudo docker run -it --rm -v ~/Projects/content:/opt/developerportal/website/content developerportal/devel`

I got error message from Jekyll:

`jekyll 3.0.0.pre.beta10 | Error:  Permission denied @ dir_initialize - .`

This is my first experience with Docker and Jekyll so I don't know what can be wrong.

Could you please help me?

**Comment by pvalena** [comment]
This should be [fixed now](https://github.com/developer-portal/website/blob/master/DEVELOPMENT.md) - there were permissions missing - the `:z` at the end.
