### ISSUE TITLE
C# logo is too small

### ISSUE THREAD

**Issue by msehnout** [developer-portal/website#49]
https://developer.fedoraproject.org/tech.html

![c_sharp](https://cloud.githubusercontent.com/assets/9369632/19146172/a4f88354-8bb2-11e6-90ed-2a22ec45b274.png)

**Comment by strzibny** [comment]
@msehnout we would welcome a pull request to fix this

**Comment by pvalena** [comment]
This is resolved by #50.

Thank you!
