### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by gustavosantiago** [developer-portal/website#57]
Would have any chance of translations into other languages?

**Comment by pvalena** [comment]
_(stumbled on this in my backlog)_
We've disscussed this with the team, but it seems there's no easy way to do it. Even if we technically could create the pages' placeholder for the translated content, for selected languages, we would still need a lot of help with manual translation (content of very technical nature cannot be reasonably translated in an automated way).

In the end, Fedora Developer Portal is community based, so if there one day **will** be community large enough to translate the pages, it's doable (we can deliver the 'placeholder'). But first, the translation of reasonable amount of pages needs  to be done.

Simplest way would be forking the repo and making changes to current content, while sending an email to [our ML](https://lists.fedoraproject.org/archives/list/developer-portal@lists.fedoraproject.org/), so we can check it and comment.

Closing for current lack of traction.
