### ISSUE TITLE
Authors are duplicated

### ISSUE THREAD

**Issue by pvalena** [developer-portal/website#77]
on [Vagrant page](https://developer.fedoraproject.org/tools/vagrant/about.html).

**Comment by pvalena** [comment]
@jackorp, would you mind taking a look?

**Comment by jackorp** [comment]
Problem is that "Josef Stribny" is there also as "Josef Str`z`ibny" and both names also have different email.

**Comment by pvalena** [comment]
Sorry, I've missed that. It works fine then.
